---
- name: Install and configure Dayz Standalone Server
  hosts: dayz_sa_server
  become: true
  tasks:
    - name: Install SteamCMD...
      get_url: "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz"
      dest: "~/steamcmd_linux.tar.gz"
      mode: '0644'
    
    - name: Extract steamcmd_linux.tar.gz
      unarchive: "~/steamcmd_linux.tar.gz"
      dest: "/opt/steamcmd"
      remote_src: yes
