---
- name: Install and configure Dayz Standalone Server
  hosts: dayz_sa_server
  gather_facts: yes
  become: true
  tasks:
    - name: System details
      debug:
        msg: "{{ ansible_facts['lsb']['release'] }}"

    - name: Update everything first
      ansible.builtin.shell: "apt-get update; apt-get upgrade -y"
      when: ansible_facts['lsb']['release'] == "18.04"

    - name: Enable i386 repository
      ansible.builtin.shell: "dpkg --add-architecture i386"
      when: ansible_facts['lsb']['release'] == "18.04"

    - name: Update apt cache for i386
      ansible.builtin.shell: "apt-get update"
      when: ansible_facts['lsb']['release'] == "18.04"

    - name: Install dependencies
      ansible.builtin.shell: "apt-get install -y apt-utils lib32gcc1 libcap-dev libcurl4 libcurl4-openssl-dev"
      when: ansible_facts['lsb']['release'] == "18.04"

    - name: Do some cleaning
      ansible.builtin.shell: "apt-get autoremove -y; rm -rf /var/lib/apt/lists/*"
      when: ansible_facts['lsb']['release'] == "18.04"

    - name: Setup user  
      ansible.builtin.user:
        name: dayz
        comment: Service Account
        create_home: yes
        uid: 1100
        groups: sudo
        shell: /bin/bash
        expires: -1
        state: present

    - name: Create directory basedir
      ansible.builtin.file:
        path: /dayz
        state: directory
        mode: '0755'
        owner: dayz
        group: dayz

    - name: Create directory basedir/server
      ansible.builtin.file:
        path: /dayz/server
        state: directory
        mode: '0755'
        owner: dayz
        group: dayz

    - name: Create directory /opt/steamcmd
      ansible.builtin.file:
        path: /opt/steamcmd
        state: directory
        mode: '0755'
