- name: Enable necessary Apache modules
      apache2_module:
        name: "{{ item }}"
        state: present
      loop:
        - fcgid
        - rewrite

    - name: Start and enable Apache service
      service:
        name: apache2
        state: started
        enabled: yes