---
- hosts: all
  become: true
  tasks:
    - name: Make sure keyrings dir exists.
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    - name: Download public key
      ansible.builtin.shell: curl -fsSL https://packages.broadcom.com/artifactory/api/security/keypair/SaltProjectKey/public | sudo tee /etc/apt/keyrings/salt-archive-keyring.pgp
    - name: Create apt source file
      ansible.builtin.shell: curl -fsSL https://github.com/saltstack/salt-install-guide/releases/latest/download/salt.sources | sudo tee /etc/apt/sources.list.d/salt.sources
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
