---
- name: Run post-install on new server.
  hosts: postinstall
  become: true
  tasks:
    - name: Update everything
      ansible.builtin.apt:
        name: "*"
        update_cache: yes
        state: latest
    - name: Install tools
      ansible.builtin.apt:
        pkg:
          - mc
          - net-tools
          - vim
          - unzip
          - unrar-free
          - locate
    - name: Update locate database
      ansible.builtin.shell: sudo updatedb
    - name: Post-Install message
      ansible.builtin.debug:
        msg: Post-Install complete.
