---
- hosts: newserver
  become: true
  tasks:
    - name: Dependencies
      ansible.builtin.apt:
        name: python3-dev
        update_cache: yes
        state: latest
    - name: Upgrade all
      ansible.builtin.apt:
        name: "*"
        update_cache: yes
        state: latest
    - name: Install packages
      ansible.builtin.apt:
        pkg:
          - python3
          - python3-dev
          - python3-venv
          - python3-pip
          - bluez
          - libffi-dev
          - libssl-dev
          - libjpeg-dev
          - zlib1g-dev
          - autoconf
          - build-essential
          - libopenjp2-7 
          - libtiff5
          - libturbojpeg0-dev
          - tzdata
          - ffmpeg
          - liblapack3
          - liblapack-dev
          - libatlas-base-dev
