---
- name: Install OpenXPKI
  hosts: openxpki_servers
  become: yes
  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - openxpki
          - openxpki-doc
          - openxpki-devel
          - apache2
          - libapache2-mod-fcgid
          - postgresql
        state: present

    - name: Enable necessary Apache modules
      apache2_module:
        name: "{{ item }}"
        state: present
      loop:
        - fcgid
        - rewrite

    - name: Start and enable Apache service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Ensure PostgreSQL is running and enabled
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Configure OpenXPKI
      template:
        src: openxpki.conf.j2
        dest: /etc/openxpki/openxpki.conf
      notify: restart openxpki

    - name: Set up database
      postgresql_db:
        name: openxpki
        owner: openxpki
        state: present

    - name: Create OpenXPKI user
      postgresql_user:
        name: openxpki
        password: yourpassword
        db: openxpki
        role_attr_flags: LOGIN
        state: present

  handlers:
    - name: restart openxpki
      service:
        name: openxpki
        state: restarted

