---
- name: Install NextCloud
  hosts: nextcloud
  become: yes
  tasks:
    - name: Update and upgrade
      ansible.builtin.apt: 
        name: "*"
        update_cache: yes
        state: latest
    - name: Install dependencies
      ansible.builtin.apt:
        pkg:
          - libapache2-mod-php
          - php8.1-gd
          - php8.1-mysql 
          - php8.1-curl
          - php8.1-mbstring
          - php8.1-intl
          - php8.1-gmp
          - php8.1-bcmath
          - php8.1-xml
          - php8.1-imagick
          - php8.1-zip
          - mysql-server
          - mysql-client-core-8.0
          - phpmyadmin

    - name: Create user
      ansible.builtin.shell: "sudo mysql -u root -e \"CREATE USER 'nextcloud'@'localhost' IDENTIFIED BY '00Ert67yu89io_';\""

    - name: Create database
      ansible.builtin.shell: "sudo mysql -u root -e 'CREATE DATABASE IF NOT EXISTS nextcloud CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci'"

    - name: Grant all privileges
      ansible.builtin.shell: "sudo mysql -u root -e \"GRANT ALL PRIVILEGES ON nextcloud.* TO 'nextcloud'@'localhost';\""

    - name: Flush privileges
      ansible.builtin.shell: "sudo mysql -u root -e 'FLUSH PRIVILEGES';"

    - name: Download NextCloud package.
      ansible.builtin.get_url: 
        url: "https://download.nextcloud.com/server/releases/latest.tar.bz2"
        dest: ~/nextcloud.tar.bz2

    - name: Unpack nextcloud archive
      ansible.builtin.unarchive:
        src: ~/nextcloud.tar.bz2
        dest: /var/www/
        remote_src: yes

    - name: Change www path
      ansible.builtin.lineinfile:
        path: /etc/apache2/sites-enabled/000-default.conf
        regexp: '^DocumentRoot  /var/www/html'
        line: 'DocumentRoot /var/www/nextcloud'

    - name: Change directory owner
      ansible.builtin.file:
        path: /var/www/nextcloud/
        recurse: yes
        owner: www-data
        group: www-data

    - name: Restart Apache2
      ansible.builtin.service:
        name: apache2
        state: restarted
