---
- name: Update packages and install basic tools on Alpine Linux
  hosts: all
  become: true
  tasks:
    - name: Update apk cache and Upgrade all packages
      ansible.builtin.apk:
        upgrade: yes
        update_cache: yes
        available: yes
      # Alpine's apk does not have a concept of "state: latest" for all packages like apt
      # `upgrade: yes` is the closest equivalent for upgrading installed packages.
      # `available: yes` ensures the latest package list is available for subsequent installs.

    - name: Install Python 3.x
      ansible.builtin.apk:
        name: "python3"
        update_cache: yes
        state: present
      # Alpine typically includes 'python3' as the primary Python installation.

    - name: Install basic tools
      ansible.builtin.apk:
        name: "{{ item }}"
        update_cache: yes
        state: present
      loop:
        - mc
        - vim
        - unzip
        - unrar
        - wget
        - curl
        - net-tools
        - whois
        - mlocate # 'locate' on Alpine is usually provided by 'mlocate'
        - jq
      # snapd and flatpak are generally not available or recommended on Alpine Linux
      # due to its design philosophy (minimalism, musl libc).
      # If you require containerized applications, consider Docker or Podman directly.
