---
- name: Update packages
  hosts: all
  become: true
  tasks:
    - name: Update cache and Upgrade all packages
      ansible.builtin.apt:
        name: "*"
        update_cache: yes
        state: latest
      environment:
        DEBIAN_FRONTEND: noninteractive
    - name: Install Python 3.x
      ansible.builtin.apt:
        name: "python3"
        update_cache: yes
        state: latest
    - name: Install basic tools
      ansible.builtin.apt:
        pkg:
          - mc
          - vim
          - snapd
          - flatpak
          - unzip
          - unrar-free
          - wget
          - curl
          - net-tools
          - whois
          - locate
