---
- hosts: all
  become: yes
  tasks:
    - name: Ensure Apache and PHP are installed
      apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
          - php-sqlite3
        state: present
        update_cache: yes

    - name: Ensure Apache is running and enabled
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Deploy the task manager script
      copy:
        src: files/cookbook.php # Your local index.php file
        dest: /var/www/html/cookbook.php
        owner: www-data
        group: www-data
        mode: '0664'

    - name: Set correct permissions on web root
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: '0775'
