---
- hosts: mkdocs
  become: true
  tasks:
    - name: Install pip3
      ansible.builtin.apt:
        name: python3-pip
        update_cache: yes
        state: latest
    - name: Install mkdocs
      ansible.builtin.shell: pip3 install mkdocs
